<a href="https://colab.research.google.com/github/DaniRodri17/dep/blob/main/keras_classification_penguin_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, Dropout

In [3]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, mean_squared_error, mean_absolute_error
from sklearn.ensemble import RandomForestClassifier

In [5]:
df = pd.read_csv('penguins_size.csv')
df.head()

,species,island,culmen_length_mm,culmen_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE


In [17]:
df.dropna(inplace=True)

In [72]:
X = df.drop('species', axis=1)
y = df['species']

# Apply one-hot encoding to categorical columns 'island' and 'sex'
X = pd.get_dummies(X, columns=['island', 'sex'], drop_first=True)

# Convert target variable 'species' to one-hot encoded format
y = pd.get_dummies(y)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [49]:
dt = RandomForestClassifier()
dt.fit(X_train, y_train)
dt_pred = dt.predict(X_test)
print(accuracy_score(y_test, dt_pred))


0.9900990099009901


In [51]:
from sklearn.metrics import classification_report
print(classification_report(y_test, dt_pred))


              precision    recall  f1-score   support

      Adelie       0.98      1.00      0.99        49
   Chinstrap       1.00      0.94      0.97        18
      Gentoo       1.00      1.00      1.00        34

    accuracy                           0.99       101
   macro avg       0.99      0.98      0.99       101
weighted avg       0.99      0.99      0.99       101



In [52]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, dt_pred))
#

[[49  0  0]
 [ 1 17  0]
 [ 0  0 34]]


In [54]:
X_train.head()

,culmen_length_mm,culmen_depth_mm,flipper_length_mm,body_mass_g,island_Dream,island_Torgersen,sex_FEMALE,sex_MALE
292,48.2,15.6,221.0,5100.0,False,False,False,True
302,47.4,14.6,212.0,4725.0,False,False,True,False
62,37.6,17.0,185.0,3600.0,False,False,True,False
181,52.8,20.0,205.0,4550.0,True,False,False,True
15,36.6,17.8,185.0,3700.0,False,True,True,False


In [117]:
model = Sequential([
    Dense(512, activation='relu', input_shape=(8,)),
    Dense(312, activation='relu'),

    Dense(3, activation='softmax')
])

model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['precision']
)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [118]:
history = model.fit(x=X_train, y=y_train,
                    validation_data=(X_test, y_test),
                    batch_size=10,
                    epochs=200)

Epoch 1/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - loss: 217.0810 - precision: 0.3393 - val_loss: 149.4727 - val_precision: 0.3366
Epoch 2/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 124.9061 - precision: 0.3098 - val_loss: 55.1778 - val_precision: 0.3366
Epoch 3/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 97.3375 - precision: 0.4081 - val_loss: 39.8577 - val_precision: 0.3366
Epoch 4/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 24.9203 - precision: 0.3718 - val_loss: 34.5790 - val_precision: 0.4851
Epoch 5/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 28.2314 - precision: 0.3828 - val_loss: 93.2910 - val_precision: 0.1782
Epoch 6/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 73.5738 - precision: 0.3098 - val_loss: 31.8778 - val_precision: 0.6634
Epoch 7/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 30.7854 - precision: 0.3609 - val_loss: 11.0875 - val_precision: 0.4851
Epoch 8/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 33.8468 - precision: